[package]
name = "chriscerie/react-spring"
description = "A modern spring-physics based animation library for Roact inspired by react-spring"
version = "1.1.6"
license = "MIT"
authors = ["chriscerie"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@^4.0"
TestEZ = "roblox/testez@^0.4"
React ="core-packages/react@17.0.1-rc.16"
ReactRoblox = "core-packages/react-roblox@17.0.1-rc.16"