[package]
name = "chriscerie/roact-spring"
description = "A modern spring-physics based animation library for Roact inspired by react-spring"
version = "1.0.1"
license = "MIT"
authors = ["chriscerie"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Roact = "roblox/roact@^1"
Promise = "evaera/promise@^4.0"
Hooks = "kampfkarren/roact-hooks@^0.4"
TestEZ = "roblox/testez@^0.4"