[package]
name = "chriscerie/roact-spring"
description = "A spring-physics based animation library for Roact inspired by react-spring"
version = "0.0.20"
license = "MIT"
authors = ["chriscerie"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Roact = "roblox/roact@^1"
Promise = "evaera/promise@^3.2"
Hooks = "kampfkarren/roact-hooks@^0.3"